// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0--rc1
// source: ststus.proto

package protorpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStutusParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StutusType    string                 `protobuf:"bytes,1,opt,name=stutus_type,json=stutusType,proto3" json:"stutus_type,omitempty"` //任意
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStutusParam) Reset() {
	*x = GetStutusParam{}
	mi := &file_ststus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStutusParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStutusParam) ProtoMessage() {}

func (x *GetStutusParam) ProtoReflect() protoreflect.Message {
	mi := &file_ststus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStutusParam.ProtoReflect.Descriptor instead.
func (*GetStutusParam) Descriptor() ([]byte, []int) {
	return file_ststus_proto_rawDescGZIP(), []int{0}
}

func (x *GetStutusParam) GetStutusType() string {
	if x != nil {
		return x.StutusType
	}
	return ""
}

type GetStutusResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Token           string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	HaveWifi        bool                   `protobuf:"varint,2,opt,name=have_wifi,json=haveWifi,proto3" json:"have_wifi,omitempty"`
	Have_4G         bool                   `protobuf:"varint,3,opt,name=have_4G,json=have4G,proto3" json:"have_4G,omitempty"`
	Gps             string                 `protobuf:"bytes,4,opt,name=gps,proto3" json:"gps,omitempty"`
	WIFI            string                 `protobuf:"bytes,5,opt,name=WIFI,proto3" json:"WIFI,omitempty"`
	USB_DEVICE_NAME string                 `protobuf:"bytes,6,opt,name=USB_DEVICE_NAME,json=USBDEVICENAME,proto3" json:"USB_DEVICE_NAME,omitempty"`
	Device_Name     string                 `protobuf:"bytes,7,opt,name=Device_Name,json=DeviceName,proto3" json:"Device_Name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStutusResult) Reset() {
	*x = GetStutusResult{}
	mi := &file_ststus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStutusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStutusResult) ProtoMessage() {}

func (x *GetStutusResult) ProtoReflect() protoreflect.Message {
	mi := &file_ststus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStutusResult.ProtoReflect.Descriptor instead.
func (*GetStutusResult) Descriptor() ([]byte, []int) {
	return file_ststus_proto_rawDescGZIP(), []int{1}
}

func (x *GetStutusResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetStutusResult) GetHaveWifi() bool {
	if x != nil {
		return x.HaveWifi
	}
	return false
}

func (x *GetStutusResult) GetHave_4G() bool {
	if x != nil {
		return x.Have_4G
	}
	return false
}

func (x *GetStutusResult) GetGps() string {
	if x != nil {
		return x.Gps
	}
	return ""
}

func (x *GetStutusResult) GetWIFI() string {
	if x != nil {
		return x.WIFI
	}
	return ""
}

func (x *GetStutusResult) GetUSB_DEVICE_NAME() string {
	if x != nil {
		return x.USB_DEVICE_NAME
	}
	return ""
}

func (x *GetStutusResult) GetDevice_Name() string {
	if x != nil {
		return x.Device_Name
	}
	return ""
}

var File_ststus_proto protoreflect.FileDescriptor

var file_ststus_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x73, 0x74, 0x73, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x70, 0x63, 0x22, 0x31, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x75, 0x74, 0x75, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x75, 0x74, 0x75, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x74, 0x75, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x76, 0x65, 0x5f, 0x77, 0x69,
	0x66, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x76, 0x65, 0x57, 0x69,
	0x66, 0x69, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x61, 0x76, 0x65, 0x5f, 0x34, 0x47, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x61, 0x76, 0x65, 0x34, 0x47, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x70, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x57, 0x49, 0x46, 0x49, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x57, 0x49, 0x46,
	0x49, 0x12, 0x26, 0x0a, 0x0f, 0x55, 0x53, 0x42, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f,
	0x4e, 0x41, 0x4d, 0x45, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x55, 0x53, 0x42, 0x44,
	0x45, 0x56, 0x49, 0x43, 0x45, 0x4e, 0x41, 0x4d, 0x45, 0x12, 0x1f, 0x0a, 0x0b, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x14, 0x5a, 0x0b, 0x2e, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x04, 0x63, 0x73, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_ststus_proto_rawDescOnce sync.Once
	file_ststus_proto_rawDescData []byte
)

func file_ststus_proto_rawDescGZIP() []byte {
	file_ststus_proto_rawDescOnce.Do(func() {
		file_ststus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ststus_proto_rawDesc), len(file_ststus_proto_rawDesc)))
	})
	return file_ststus_proto_rawDescData
}

var file_ststus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ststus_proto_goTypes = []any{
	(*GetStutusParam)(nil),  // 0: protorpc.GetStutusParam
	(*GetStutusResult)(nil), // 1: protorpc.GetStutusResult
}
var file_ststus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ststus_proto_init() }
func file_ststus_proto_init() {
	if File_ststus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ststus_proto_rawDesc), len(file_ststus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ststus_proto_goTypes,
		DependencyIndexes: file_ststus_proto_depIdxs,
		MessageInfos:      file_ststus_proto_msgTypes,
	}.Build()
	File_ststus_proto = out.File
	file_ststus_proto_goTypes = nil
	file_ststus_proto_depIdxs = nil
}
