// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfAdmin/internal/dao/internal"
)

// internalABTokensDao is an internal type for wrapping the internal DAO implementation.
type internalABTokensDao = *internal.ABTokensDao

// aBTokensDao is the data access object for the table ABTokens.
// You can define custom methods on it to extend its functionality as needed.
type aBTokensDao struct {
	internalABTokensDao
}

var (
	// ABTokens is a globally accessible object for table ABTokens operations.
	ABTokens = aBTokensDao{
		internal.NewABTokensDao(),
	}
)

// Add your custom methods and functionality below.
