// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfAdmin/internal/dao/internal"
)

// internalBannedTokensDao is an internal type for wrapping the internal DAO implementation.
type internalBannedTokensDao = *internal.BannedTokensDao

// bannedTokensDao is the data access object for the table BannedTokens.
// You can define custom methods on it to extend its functionality as needed.
type bannedTokensDao struct {
	internalBannedTokensDao
}

var (
	// BannedTokens is a globally accessible object for table BannedTokens operations.
	BannedTokens = bannedTokensDao{
		internal.NewBannedTokensDao(),
	}
)

// Add your custom methods and functionality below.
