// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfAdmin/internal/dao/internal"
)

// internalPrintServerDao is an internal type for wrapping the internal DAO implementation.
type internalPrintServerDao = *internal.PrintServerDao

// printServerDao is the data access object for the table PrintServer.
// You can define custom methods on it to extend its functionality as needed.
type printServerDao struct {
	internalPrintServerDao
}

var (
	// PrintServer is a globally accessible object for table PrintServer operations.
	PrintServer = printServerDao{
		internal.NewPrintServerDao(),
	}
)

// Add your custom methods and functionality below.
