// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfAdmin/internal/dao/internal"
)

// internalSystemMenusDao is an internal type for wrapping the internal DAO implementation.
type internalSystemMenusDao = *internal.SystemMenusDao

// systemMenusDao is the data access object for the table SystemMenus.
// You can define custom methods on it to extend its functionality as needed.
type systemMenusDao struct {
	internalSystemMenusDao
}

var (
	// SystemMenus is a globally accessible object for table SystemMenus operations.
	SystemMenus = systemMenusDao{
		internal.NewSystemMenusDao(),
	}
)

// Add your custom methods and functionality below.
