// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ststus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace cspb {

  /// <summary>Holder for reflection information generated from ststus.proto</summary>
  public static partial class StstusReflection {

    #region Descriptor
    /// <summary>File descriptor for ststus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StstusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxzdHN0dXMucHJvdG8SCHByb3RvcnBjIiUKDkdldFN0dXR1c1BhcmFtEhMK",
            "C3N0dXR1c190eXBlGAEgASgJIo0BCg9HZXRTdHV0dXNSZXN1bHQSDQoFdG9r",
            "ZW4YASABKAkSEQoJaGF2ZV93aWZpGAIgASgIEg8KB2hhdmVfNEcYAyABKAgS",
            "CwoDZ3BzGAQgASgJEgwKBFdJRkkYBSABKAkSFwoPVVNCX0RFVklDRV9OQU1F",
            "GAYgASgJEhMKC0RldmljZV9OYW1lGAcgASgJQhRaCy4uL3Byb3RvcnBjqgIE",
            "Y3NwYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::cspb.GetStutusParam), global::cspb.GetStutusParam.Parser, new[]{ "StutusType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::cspb.GetStutusResult), global::cspb.GetStutusResult.Parser, new[]{ "Token", "HaveWifi", "Have4G", "Gps", "WIFI", "USBDEVICENAME", "DeviceName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetStutusParam : pb::IMessage<GetStutusParam>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetStutusParam> _parser = new pb::MessageParser<GetStutusParam>(() => new GetStutusParam());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetStutusParam> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::cspb.StstusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStutusParam() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStutusParam(GetStutusParam other) : this() {
      stutusType_ = other.stutusType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStutusParam Clone() {
      return new GetStutusParam(this);
    }

    /// <summary>Field number for the "stutus_type" field.</summary>
    public const int StutusTypeFieldNumber = 1;
    private string stutusType_ = "";
    /// <summary>
    ///任意
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StutusType {
      get { return stutusType_; }
      set {
        stutusType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetStutusParam);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetStutusParam other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StutusType != other.StutusType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StutusType.Length != 0) hash ^= StutusType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StutusType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StutusType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StutusType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StutusType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StutusType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StutusType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetStutusParam other) {
      if (other == null) {
        return;
      }
      if (other.StutusType.Length != 0) {
        StutusType = other.StutusType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StutusType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StutusType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetStutusResult : pb::IMessage<GetStutusResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetStutusResult> _parser = new pb::MessageParser<GetStutusResult>(() => new GetStutusResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetStutusResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::cspb.StstusReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStutusResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStutusResult(GetStutusResult other) : this() {
      token_ = other.token_;
      haveWifi_ = other.haveWifi_;
      have4G_ = other.have4G_;
      gps_ = other.gps_;
      wIFI_ = other.wIFI_;
      uSBDEVICENAME_ = other.uSBDEVICENAME_;
      deviceName_ = other.deviceName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStutusResult Clone() {
      return new GetStutusResult(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "have_wifi" field.</summary>
    public const int HaveWifiFieldNumber = 2;
    private bool haveWifi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HaveWifi {
      get { return haveWifi_; }
      set {
        haveWifi_ = value;
      }
    }

    /// <summary>Field number for the "have_4G" field.</summary>
    public const int Have4GFieldNumber = 3;
    private bool have4G_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Have4G {
      get { return have4G_; }
      set {
        have4G_ = value;
      }
    }

    /// <summary>Field number for the "gps" field.</summary>
    public const int GpsFieldNumber = 4;
    private string gps_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Gps {
      get { return gps_; }
      set {
        gps_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "WIFI" field.</summary>
    public const int WIFIFieldNumber = 5;
    private string wIFI_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WIFI {
      get { return wIFI_; }
      set {
        wIFI_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "USB_DEVICE_NAME" field.</summary>
    public const int USBDEVICENAMEFieldNumber = 6;
    private string uSBDEVICENAME_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string USBDEVICENAME {
      get { return uSBDEVICENAME_; }
      set {
        uSBDEVICENAME_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Device_Name" field.</summary>
    public const int DeviceNameFieldNumber = 7;
    private string deviceName_ = "";
    /// <summary>
    /// string Seris_ID = 8;
    /// string 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceName {
      get { return deviceName_; }
      set {
        deviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetStutusResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetStutusResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      if (HaveWifi != other.HaveWifi) return false;
      if (Have4G != other.Have4G) return false;
      if (Gps != other.Gps) return false;
      if (WIFI != other.WIFI) return false;
      if (USBDEVICENAME != other.USBDEVICENAME) return false;
      if (DeviceName != other.DeviceName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (HaveWifi != false) hash ^= HaveWifi.GetHashCode();
      if (Have4G != false) hash ^= Have4G.GetHashCode();
      if (Gps.Length != 0) hash ^= Gps.GetHashCode();
      if (WIFI.Length != 0) hash ^= WIFI.GetHashCode();
      if (USBDEVICENAME.Length != 0) hash ^= USBDEVICENAME.GetHashCode();
      if (DeviceName.Length != 0) hash ^= DeviceName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (HaveWifi != false) {
        output.WriteRawTag(16);
        output.WriteBool(HaveWifi);
      }
      if (Have4G != false) {
        output.WriteRawTag(24);
        output.WriteBool(Have4G);
      }
      if (Gps.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Gps);
      }
      if (WIFI.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(WIFI);
      }
      if (USBDEVICENAME.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(USBDEVICENAME);
      }
      if (DeviceName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DeviceName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (HaveWifi != false) {
        output.WriteRawTag(16);
        output.WriteBool(HaveWifi);
      }
      if (Have4G != false) {
        output.WriteRawTag(24);
        output.WriteBool(Have4G);
      }
      if (Gps.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Gps);
      }
      if (WIFI.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(WIFI);
      }
      if (USBDEVICENAME.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(USBDEVICENAME);
      }
      if (DeviceName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DeviceName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (HaveWifi != false) {
        size += 1 + 1;
      }
      if (Have4G != false) {
        size += 1 + 1;
      }
      if (Gps.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Gps);
      }
      if (WIFI.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WIFI);
      }
      if (USBDEVICENAME.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(USBDEVICENAME);
      }
      if (DeviceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetStutusResult other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.HaveWifi != false) {
        HaveWifi = other.HaveWifi;
      }
      if (other.Have4G != false) {
        Have4G = other.Have4G;
      }
      if (other.Gps.Length != 0) {
        Gps = other.Gps;
      }
      if (other.WIFI.Length != 0) {
        WIFI = other.WIFI;
      }
      if (other.USBDEVICENAME.Length != 0) {
        USBDEVICENAME = other.USBDEVICENAME;
      }
      if (other.DeviceName.Length != 0) {
        DeviceName = other.DeviceName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 16: {
            HaveWifi = input.ReadBool();
            break;
          }
          case 24: {
            Have4G = input.ReadBool();
            break;
          }
          case 34: {
            Gps = input.ReadString();
            break;
          }
          case 42: {
            WIFI = input.ReadString();
            break;
          }
          case 50: {
            USBDEVICENAME = input.ReadString();
            break;
          }
          case 58: {
            DeviceName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 16: {
            HaveWifi = input.ReadBool();
            break;
          }
          case 24: {
            Have4G = input.ReadBool();
            break;
          }
          case 34: {
            Gps = input.ReadString();
            break;
          }
          case 42: {
            WIFI = input.ReadString();
            break;
          }
          case 50: {
            USBDEVICENAME = input.ReadString();
            break;
          }
          case 58: {
            DeviceName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
